### PR TITLE
Upgrade packages to NVM 1.1.7

### LINKED ISSUE #8: Upgrade to version 1.1.6
Version 1.1.6 is out for a while already. Would you please update? https://github.com/coreybutler/nvm-windows/releases/tag/1.1.6

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #8 

I think this should work!

### CODE REVIEW

**Comment by arieljannai** [comment]
Thanks! Checking it today 👌

**Comment by arieljannai** [comment]
@espoelstra Can you push the updated package of `nvm` to chocolatey? :)
I pushed `nvm.portable` and it was approved (and now online).

**Comment by espoelstra** [comment]
For some reason Appveyor is reporting a permissions error when I try to trigger a new build of `nvm` against the repo from my phone. I'll check it out from a larger screen when I get into the office and see what's up.

**Comment by arieljannai** [comment]
Thanks! You can also set me as a maintainer and I'll do it

**Pull request merged**
