### PR TITLE
Updated to 1.1.1 and refactored

### PR DESCRIPTION
**Pull request by espoelstra**
Tested this working locally. Cleans up node installs when uninstalled, disables nvm symlink during upgrades (not sure if we can detect if it was upgraded and turn it back on), removes environment variables on uninstall, keeps settings.txt between upgrades (which are few and far between currently).

### CODE REVIEW

**Comment by arieljannai** [comment]
Thanks, I didn't had time for that.
I will look at this that weekend!

**Comment by arieljannai** [comment]
@espoelstra It looks good, but unfortunately I couldn't test it cause I did it on the way.
I've just start the year at the university, so I don't believe I'll have time soon.

I will give you permissions on the package at [chocolatey.org](https://chocolatey.org/) so you'll be able to upload it and receive the moderators feedback.
Is it ok?
If so, what's your chocolatey user? is it the same as here?

**Comment by espoelstra** [comment]
Yeah, espoelstra is my Chocolatey username as well. I'd be happy to help maintain the package, I'm hoping we can use it in our TeamCity build pipeline to prevent various projects using node/npm from conflicting with each other's dependencies.

**Comment by arieljannai** [comment]
I've invited you to collaborate in this github repo and in the chocolatey package 😄

**Comment by espoelstra** [comment]
Thanks @arieljannai I did a couple quick fixes on the removal of variables from the PATH yesterday after I noticed a bug while working on another package. I'll merge this and push the package up to Chocolatey and see what the verifier has to say.

**Comment by arieljannai** [comment]
great, good to hear!

**Comment by espoelstra** [comment]
Not sure if I'll need access to the nvm package in Chocolatey as well since it's just a virtual that should always point to the latest nvm.portable. I'm going to try to upload the built version shortly, I'm also trying to add AppVeyor into the project to build the package(s) automatically upon pull requests and commits for easier maintenance.

**Comment by arieljannai** [comment]
If you were planning on uploading on the name **nvm** or **nvm-windows**, they are both taken and rejected. So maybe we can contact a maintainer from chocolatey to take one of those names

**Pull request merged**
